#include "generic_vector.h"
#include "check.h"
#include "common/generic_vector.h"


void test_generic_vector()
{
	WS_GEN_VECTOR(v, int);
	WS_GEN_VECTOR_CREATE(v);

	TEST_EXPECT(WS_GEN_VECTOR_SIZE(v) == 0);
	WS_GEN_VECTOR_PUSH_BACK(v, 2);
	TEST_EXPECT(WS_GEN_VECTOR_SIZE(v) == 1);
	TEST_EXPECT(WS_GEN_VECTOR_CAPACITY(v) >= 1);
	WS_GEN_VECTOR_PUSH_BACK(v, 3);
	TEST_EXPECT(WS_GEN_VECTOR_SIZE(v) == 2);
	TEST_EXPECT(WS_GEN_VECTOR_CAPACITY(v) >= 2);
	WS_GEN_VECTOR_PUSH_BACK(v, 5);
	TEST_EXPECT(WS_GEN_VECTOR_SIZE(v) == 3);
	TEST_EXPECT(WS_GEN_VECTOR_CAPACITY(v) >= 3);
	WS_GEN_VECTOR_PUSH_BACK(v, 7);
	TEST_EXPECT(WS_GEN_VECTOR_SIZE(v) == 4);
	TEST_EXPECT(WS_GEN_VECTOR_CAPACITY(v) >= 4);

	TEST_EXPECT(WS_GEN_VECTOR_DATA(v)[0] == 2);
	TEST_EXPECT(WS_GEN_VECTOR_DATA(v)[1] == 3);
	TEST_EXPECT(WS_GEN_VECTOR_DATA(v)[2] == 5);
	TEST_EXPECT(WS_GEN_VECTOR_DATA(v)[3] == 7);

	WS_GEN_VECTOR_DESTROY(v);
}
